// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbadpsgbhjdruzjobvct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiYWRwc2diaGpkcnV6am9idmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDg0MjQsImV4cCI6MjA2NjUyNDQyNH0.AtZqEBs-4y9k5ZVGI6Ctg8_t8fdMxz-sKoS3kzVMt8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);